// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/herd/models.proto

package herd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Herd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	AccountId     string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Herd) Reset() {
	*x = Herd{}
	mi := &file_api_herd_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Herd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Herd) ProtoMessage() {}

func (x *Herd) ProtoReflect() protoreflect.Message {
	mi := &file_api_herd_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Herd.ProtoReflect.Descriptor instead.
func (*Herd) Descriptor() ([]byte, []int) {
	return file_api_herd_models_proto_rawDescGZIP(), []int{0}
}

func (x *Herd) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Herd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Herd) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Herd) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Herd) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Herd) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_herd_models_proto protoreflect.FileDescriptor

const file_api_herd_models_proto_rawDesc = "" +
	"\n" +
	"\x15api/herd/models.proto\x12\x06models\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x01\n" +
	"\x04Herd\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\x0fZ\rapi/herd;herdb\x06proto3"

var (
	file_api_herd_models_proto_rawDescOnce sync.Once
	file_api_herd_models_proto_rawDescData []byte
)

func file_api_herd_models_proto_rawDescGZIP() []byte {
	file_api_herd_models_proto_rawDescOnce.Do(func() {
		file_api_herd_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_herd_models_proto_rawDesc), len(file_api_herd_models_proto_rawDesc)))
	})
	return file_api_herd_models_proto_rawDescData
}

var file_api_herd_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_herd_models_proto_goTypes = []any{
	(*Herd)(nil),                  // 0: models.Herd
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_api_herd_models_proto_depIdxs = []int32{
	1, // 0: models.Herd.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: models.Herd.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_herd_models_proto_init() }
func file_api_herd_models_proto_init() {
	if File_api_herd_models_proto != nil {
		return
	}
	file_api_herd_models_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_herd_models_proto_rawDesc), len(file_api_herd_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_herd_models_proto_goTypes,
		DependencyIndexes: file_api_herd_models_proto_depIdxs,
		MessageInfos:      file_api_herd_models_proto_msgTypes,
	}.Build()
	File_api_herd_models_proto = out.File
	file_api_herd_models_proto_goTypes = nil
	file_api_herd_models_proto_depIdxs = nil
}
