// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/herd/service.proto

package herd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHerdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHerdRequest) Reset() {
	*x = CreateHerdRequest{}
	mi := &file_api_herd_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHerdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHerdRequest) ProtoMessage() {}

func (x *CreateHerdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_herd_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHerdRequest.ProtoReflect.Descriptor instead.
func (*CreateHerdRequest) Descriptor() ([]byte, []int) {
	return file_api_herd_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHerdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHerdRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateHerdRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type CreateHerdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Herd          *Herd                  `protobuf:"bytes,1,opt,name=herd,proto3" json:"herd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHerdResponse) Reset() {
	*x = CreateHerdResponse{}
	mi := &file_api_herd_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHerdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHerdResponse) ProtoMessage() {}

func (x *CreateHerdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_herd_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHerdResponse.ProtoReflect.Descriptor instead.
func (*CreateHerdResponse) Descriptor() ([]byte, []int) {
	return file_api_herd_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHerdResponse) GetHerd() *Herd {
	if x != nil {
		return x.Herd
	}
	return nil
}

type GetHerdListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	AccountId     string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHerdListRequest) Reset() {
	*x = GetHerdListRequest{}
	mi := &file_api_herd_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHerdListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHerdListRequest) ProtoMessage() {}

func (x *GetHerdListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_herd_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHerdListRequest.ProtoReflect.Descriptor instead.
func (*GetHerdListRequest) Descriptor() ([]byte, []int) {
	return file_api_herd_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetHerdListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetHerdListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHerdListRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetHerdListRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetHerdListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Herds         []*Herd                `protobuf:"bytes,1,rep,name=herds,proto3" json:"herds,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHerdListResponse) Reset() {
	*x = GetHerdListResponse{}
	mi := &file_api_herd_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHerdListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHerdListResponse) ProtoMessage() {}

func (x *GetHerdListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_herd_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHerdListResponse.ProtoReflect.Descriptor instead.
func (*GetHerdListResponse) Descriptor() ([]byte, []int) {
	return file_api_herd_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetHerdListResponse) GetHerds() []*Herd {
	if x != nil {
		return x.Herds
	}
	return nil
}

func (x *GetHerdListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_api_herd_service_proto protoreflect.FileDescriptor

const file_api_herd_service_proto_rawDesc = "" +
	"\n" +
	"\x16api/herd/service.proto\x12\x04herd\x1a\x15api/herd/models.proto\"}\n" +
	"\x11CreateHerdRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountIdB\x0e\n" +
	"\f_description\"6\n" +
	"\x12CreateHerdResponse\x12 \n" +
	"\x04herd\x18\x01 \x01(\v2\f.models.HerdR\x04herd\"u\n" +
	"\x12GetHerdListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\"Z\n" +
	"\x13GetHerdListResponse\x12\"\n" +
	"\x05herds\x18\x01 \x03(\v2\f.models.HerdR\x05herds\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\x92\x01\n" +
	"\vHerdService\x12?\n" +
	"\n" +
	"CreateHerd\x12\x17.herd.CreateHerdRequest\x1a\x18.herd.CreateHerdResponse\x12B\n" +
	"\vGetHerdList\x12\x18.herd.GetHerdListRequest\x1a\x19.herd.GetHerdListResponseB\x0fZ\rapi/herd;herdb\x06proto3"

var (
	file_api_herd_service_proto_rawDescOnce sync.Once
	file_api_herd_service_proto_rawDescData []byte
)

func file_api_herd_service_proto_rawDescGZIP() []byte {
	file_api_herd_service_proto_rawDescOnce.Do(func() {
		file_api_herd_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_herd_service_proto_rawDesc), len(file_api_herd_service_proto_rawDesc)))
	})
	return file_api_herd_service_proto_rawDescData
}

var file_api_herd_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_herd_service_proto_goTypes = []any{
	(*CreateHerdRequest)(nil),   // 0: herd.CreateHerdRequest
	(*CreateHerdResponse)(nil),  // 1: herd.CreateHerdResponse
	(*GetHerdListRequest)(nil),  // 2: herd.GetHerdListRequest
	(*GetHerdListResponse)(nil), // 3: herd.GetHerdListResponse
	(*Herd)(nil),                // 4: models.Herd
}
var file_api_herd_service_proto_depIdxs = []int32{
	4, // 0: herd.CreateHerdResponse.herd:type_name -> models.Herd
	4, // 1: herd.GetHerdListResponse.herds:type_name -> models.Herd
	0, // 2: herd.HerdService.CreateHerd:input_type -> herd.CreateHerdRequest
	2, // 3: herd.HerdService.GetHerdList:input_type -> herd.GetHerdListRequest
	1, // 4: herd.HerdService.CreateHerd:output_type -> herd.CreateHerdResponse
	3, // 5: herd.HerdService.GetHerdList:output_type -> herd.GetHerdListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_herd_service_proto_init() }
func file_api_herd_service_proto_init() {
	if File_api_herd_service_proto != nil {
		return
	}
	file_api_herd_models_proto_init()
	file_api_herd_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_herd_service_proto_rawDesc), len(file_api_herd_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_herd_service_proto_goTypes,
		DependencyIndexes: file_api_herd_service_proto_depIdxs,
		MessageInfos:      file_api_herd_service_proto_msgTypes,
	}.Build()
	File_api_herd_service_proto = out.File
	file_api_herd_service_proto_goTypes = nil
	file_api_herd_service_proto_depIdxs = nil
}
